## Logistic regrssion

In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
import pandas as pd
sns.set(style="whitegrid", color_codes=True)

In [3]:
dataset = pd.read_csv("LR_train_02.csv")

In [4]:
dataset

       Strike     Stock  option_price    IV      Time
0     21000.0  18127.35         27.60  0.14  0.265753
1     22000.0  18127.35         12.25  0.15  0.265753
2     23000.0  18127.35          9.40  0.18  0.265753
3     24000.0  18127.35          6.85  0.20  0.265753
4     18000.0  18127.35        789.10  0.11  0.265753
...       ...       ...           ...   ...       ...
4373  16900.0  16945.05        133.00  0.12  0.013699
4374  16950.0  16945.05        106.45  0.12  0.013699
4375  17000.0  16945.05         83.00  0.12  0.013699
4376  17050.0  16945.05         63.20  0.12  0.013699
4377  16700.0  16945.05        278.40  0.10  0.013699

[4378 rows x 5 columns]